"""OAuth DTO models module.

This module contains data transfer objects for OAuth authentication operations
including configuration, callbacks, login responses, and token management.
"""

from pydantic import BaseModel, Field


class OAuthConfigResponse(BaseModel):
    """OAuth configuration response model.

    Used for frontend direct redirect to OAuth provider.
    Contains necessary configuration for client-side OAuth flow.
    """

    client_id: str = Field(description="Kakao app Client ID")
    redirect_uri: str = Field(description="Callback URL to receive authorization code")
    authorize_url: str = Field(description="Kakao authorization page URL")
    state: str = Field(description="Signed state value for CSRF protection (generated by backend)")


class OAuthCallbackRequest(BaseModel):
    """OAuth callback request model.

    Used for processing OAuth callback query parameters
    from the OAuth provider.
    """

    code: str = Field(description="Authorization code")
    state: str | None = Field(default=None, description="CSRF protection state value")
    error: str | None = Field(default=None, description="Error code")
    error_description: str | None = Field(default=None, description="Error description")


class OAuthLoginResponse(BaseModel):
    """Social login success response model.

    Web (cookie) mode: access/refresh tokens are delivered via HttpOnly cookies
    and the token fields below stay None. App (``X-Client-Type: native``) mode:
    tokens are returned in the body instead of cookies.
    """

    is_new_user: bool = Field(description="Whether user is newly registered")
    access_token: str | None = Field(default=None, description="JWT access token (app/native mode only)")
    refresh_token: str | None = Field(default=None, description="JWT refresh token (app/native mode only)")
    token_type: str = Field(default="Bearer", description="Token type")


class OAuthUserInfo(BaseModel):
    """OAuth user information model.

    Contains user information retrieved from OAuth provider (Kakao).
    """

    provider_account_id: str = Field(description="Kakao user unique ID")
    nickname: str = Field(description="User nickname")
    profile_image_url: str | None = Field(default=None, description="Profile image URL")


class OAuthErrorResponse(BaseModel):
    """OAuth error response model.

    Used for standardized OAuth error responses.
    """

    error: str = Field(description="Error code")
    error_description: str = Field(description="Detailed error description")


class TokenRefreshResponse(BaseModel):
    """Token refresh response model (RTR).

    Used for Refresh Token Rotation responses.
    Contains new access token information.
    """

    access_token: str = Field(description="New JWT Access Token")
    refresh_token: str | None = Field(
        default=None,
        description="New rotated refresh token — returned only in app/Bearer mode; omitted (None) in web/cookie mode",
    )
    token_type: str = Field(default="Bearer", description="Token type")


class AuthMeResponse(BaseModel):
    """Authentication status check response."""

    account_id: str = Field(description="Account ID")
