"""Lifestyle guide model module.

This module defines the LifestyleGuide model for storing GPT-generated
medication-lifestyle interaction guides per profile, plus the lifecycle
status enum used by the async (RQ) generation pipeline.
"""

from enum import StrEnum

from tortoise import fields, models


class GuideCategory(StrEnum):
  """Lifestyle guide category enumeration.

  Represents the five health domains covered by the lifestyle guide.
  """

  DIET = "diet"
  SLEEP = "sleep"
  EXERCISE = "exercise"
  SYMPTOM = "symptom"
  INTERACTION = "interaction"


class LifestyleGuideStatusValue(StrEnum):
  """Async generation lifecycle status for ``lifestyle_guides`` rows.

  - ``pending``: FastAPI inserted the row + RQ enqueued; ai-worker not done yet.
  - ``ready``: ai-worker filled ``content`` + bulk-created challenges.
  - ``no_active_meds``: No active medications at generation time (terminal).
  - ``failed``: LLM call/parse error (terminal).
  """

  PENDING = "pending"
  READY = "ready"
  NO_ACTIVE_MEDS = "no_active_meds"
  FAILED = "failed"


class LifestyleGuide(models.Model):
  """Lifestyle guide model for GPT-generated medication lifestyle advice.

  Stores the full JSON guide generated by GPT-4o-mini based on the user's
  active medications. Each guide is a snapshot tied to a specific set of
  medications at generation time.

  The row is INSERTed by FastAPI in ``pending`` state with empty content,
  then ai-worker UPDATEs it to a terminal state once the LLM call finishes.

  Attributes:
      id: Primary key UUID.
      profile: Foreign key to Profile model.
      status: Async generation lifecycle status.
      content: Full GPT-generated guide as JSON (empty until status='ready').
      medication_snapshot: JSON snapshot of active medications at generation time.
      input_fingerprint: SHA-256 hex of the canonical input (약물 set + 설문 +
          프롬프트 버전). 같은 fingerprint 의 ready 가이드가 이미 있으면
          서비스 단에서 새로 생성하지 않고 그것을 재사용한다.
      created_at: Row insertion timestamp (= enqueue time).
      processed_at: ai-worker terminal-status set time.
  """

  id = fields.UUIDField(primary_key=True)
  profile = fields.ForeignKeyField(
    "models.Profile",
    related_name="lifestyle_guides",
    description="Guide owner profile",
  )
  # 처방전 그룹 — 신규 가이드는 set 되어 처방전 컨텍스트로 묶임.
  # 옛 row (마이그레이션 #24 시점 이전 가이드) 는 NULL — 처방전 단위 아님.
  prescription_group = fields.ForeignKeyField(
    "models.PrescriptionGroup",
    related_name="lifestyle_guides",
    null=True,
    description="가이드가 만들어진 처방전 그룹 (신규부터 set)",
  )

  status = fields.CharField(
    max_length=16,
    default=LifestyleGuideStatusValue.PENDING.value,
    description="Async generation status (pending/ready/no_active_meds/failed)",
  )

  # Full GPT response stored as JSON — 5-category structure (empty until ready)
  content = fields.JSONField(description="GPT-generated guide content (5 categories)")

  # Snapshot of active medications at the time of generation
  # Used for medication change detection (future scope)
  medication_snapshot = fields.JSONField(description="Active medication list at guide generation time")

  # Canonical input fingerprint — 동일 입력 dedupe 용 (Phase B)
  input_fingerprint = fields.CharField(
    max_length=64,
    null=True,
    description="SHA-256 hex of canonical input (medications + survey + prompt_ver)",
  )

  # 가이드 생성 시 LLM 으로 한 번에 15개 챌린지를 받아 DB 에 저장하고,
  # 사용자에게는 5개씩 점진 노출. 이 컬럼은 *현재까지 노출한 챌린지 수*.
  # 초기값 5 (가이드 ready 시점에 첫 5개 노출 상태). "추천 챌린지 더 보기"
  # 클릭 시 +5 (단일 UPDATE, LLM 호출 X). 15 도달 시 더 이상 더보기 불가.
  # — 이 정책은 LLM 비용 절감 + 챌린지 일관성 보존 목적.
  revealed_challenge_count = fields.IntField(
    default=5,
    description="현재까지 사용자에게 노출한 챌린지 개수 (5 → 10 → 15)",
  )

  created_at = fields.DatetimeField(auto_now_add=True)
  processed_at = fields.DatetimeField(null=True, description="Terminal-status set time")

  class Meta:
    table = "lifestyle_guides"
    indexes = (
      ("profile_id", "created_at"),
      ("profile_id", "input_fingerprint"),
    )
